# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('glassType', models.CharField(max_length=50)),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='ing',
            field=models.ManyToManyField(through='drink_app.Amount', to='drink_app.Ing'),
        ),
        migrations.AddField(
            model_name='amount',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink_app.Drink'),
        ),
        migrations.AddField(
            model_name='amount',
            name='ing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink_app.Ing'),
        ),
    ]
